---
type: cnct
uniqueId: pipeline-munnin.cluster.cnct.io
displayName: muninn.cluster.cnct.io
description: Cluster Configuration Repository
apiUrl: "https://api.github.com"
org: samsung-cnct
repo: munnin.cluster.cnct.io
keepDays: 10
credentials: github-access
