---
type: cnct
uniqueId: pipeline-cluster-api-provider-ssh-tests
displayName: cluster-api-provider-ssh-tests
description: Tests for a simple Cluster API provisioner using SSH
apiUrl: "https://api.github.com"
org: samsung-cnct
repo: cluster-api-provider-ssh-tests
keepDays: 10
credentials: github-access
